// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDedqy85CPaG3R68eFlzeBR3K39KN_3Nog',
    appId: '1:626878627787:android:9ab5daf4e3860992e9004e',
    messagingSenderId: '626878627787',
    projectId: 'friendlychat-3dcf1',
    databaseURL: 'https://friendlychat-3dcf1-default-rtdb.firebaseio.com',
    storageBucket: 'friendlychat-3dcf1.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgriVlhLSS2N1yZTUJos6JBmG7mENLeW8',
    appId: '1:626878627787:ios:bc36210e16347000e9004e',
    messagingSenderId: '626878627787',
    projectId: 'friendlychat-3dcf1',
    databaseURL: 'https://friendlychat-3dcf1-default-rtdb.firebaseio.com',
    storageBucket: 'friendlychat-3dcf1.appspot.com',
    androidClientId: '626878627787-e522sjot2nfs3vgoq97cr3jtuol5kocb.apps.googleusercontent.com',
    iosClientId: '626878627787-su49tnr443sioqbcs3u21l2t62cchffs.apps.googleusercontent.com',
    iosBundleId: 'com.aichat.aichat',
  );
}
